CREATE DATABASE IF NOT EXISTS MyDb;
USE MyDb;
CREATE TABLE IF NOT EXISTS MyDb.foodratings (
name STRING COMMENT 'name',
food1 INT COMMENT 'food1',
food2 INT COMMENT 'food2',
food3 INT COMMENT 'food3',
food4 INT COMMENT 'food4',
id INT COMMENT 'id')
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

